[package]
name = "godot"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]

[dependencies]
libc = "0.2"
godot-sys = {path = "./godot-sys" }
bitflags = "1.0"

[build-dependencies]
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"